#pragma once

// Auto-generated by CI from the VERSION file at the repo root.
// Update this file manually before tagging a local release build.
// Do not edit the CI-generated copy.

namespace ImageScraper
{
    constexpr int VERSION_MAJOR = 0;
    constexpr int VERSION_MINOR = 1;
    constexpr int VERSION_PATCH = 0;
    constexpr const char* VERSION_STRING = "0.1.0";
}
