/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123955-g6c114bd6fa-20260414"
#endif /* AVUTIL_FFVERSION_H */
